spring:
  application:
    name: gateway-demo
  cloud:
    gateway:
      enabled: true
      routes:
        #路径的匹配，StripPrefix代表信
        - id: path_route
          predicates:
            - Path=/b
          filters:
            - StripPrefix=1
          uri: https://www.bilibili.com
        #cookie的匹配
        - id: cookie_route
          predicates:
            - Cookie=chocolate,ch.p
          uri: https://www.bilibili.com
        #请求头匹配
        - id: header_route
          predicates:
            - Header=X-Request-Id, \d+
          uri: https://www.bilibili.com
        # 组合匹配
        - id: compose
          predicates:
            - Path=/compose
            - Header=name, cong
          uri: https://www.bilibili.com
          filters:
            - StripPrefix=1
        #路径的匹配，StripPrefix代表信
        - id: path_route3
          predicates:
            - Path=/c
          filters:
            - StripPrefix=1
          uri: https://www.csdn.net/